---

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:
  commits:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - run: cargo binstall cocogitto --no-confirm
      - run: cog check
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - run: cargo llvm-cov --all-features --fail-under-lines 100 --ignore-filename-regex 'source/main\.rs$' --workspace
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fmt --all --check
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: taplo fmt --check --diff
  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo clippy --all-features --all-targets --workspace
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup toolchain install 1.85 --no-self-update --profile minimal
      - run: cargo +1.85 check --all-features --workspace
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo test --all-features --all-targets --workspace

name: CI

'on':
  pull_request: null
  push:
    branches: [base]
